import { useRouter } from "next/router";
import Header from "../components/Header/Header";
import ProductFeed from "../components/ProductFeed";
import { motion } from "framer-motion";
import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/footer/Footer"

export async function getServerSideProps(context) {
  const { query } = context.query;
  const products = await fetch(
    `https://fakestoreapi.com/products`
  ).then((res) => res.json());

  const filteredProducts = products.filter((product) =>
    product.title.toLowerCase().includes(query.toLowerCase())
  );

  return {
    props: {
      products: filteredProducts,
    },
  };
}

function Search({ products }) {
  const router = useRouter();

  return (
    <motion.div
      className="bg-gray-100"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://pngimg.com/uploads/amazon/amazon_PNG5.png"
        />
      </Head>
      <Header />
      <div className="relative">
        <Banner />
        {products.length === 0 && (
          <div className="absolute top-0 left-0 w-full text-center mt-80">
            <h1 className="text-3xl font-bold">No products found</h1>
            <p className="mt-4">Please try searching with different keywords.</p>
          </div>
        )}
      </div>
      <main className="max-w-screen-2xl mx-auto">
        {products.length > 0 && <ProductFeed products={products} />}
      </main>
      <Footer />
    </motion.div>
  );
}

export default Search;
