import { useRouter } from 'next/router';
import Header from '../../components/Header/Header';
import ProductDetail from '../../components/ProductDetail';
import { FaArrowLeft } from "react-icons/fa";
import Head from "next/head";
import Footer from "../../components/footer/Footer";
import { Dialog, Transition } from "@headlessui/react";
import { useState, Fragment } from "react";

export async function getServerSideProps(context) {
  const { pid } = context.query;
  const product = await fetch(
    `https://fakestoreapi.com/products/${pid}`
  ).then((res) => res.json());

  return {
    props: {
      product,
    },
  };
}

function ProductPage({ product }) {
  const router = useRouter();
  const rating = parseInt(router.query.rating, 10) || Math.floor(product.rating.rate);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const closeModal = () => setIsModalOpen(false);
  const openModal = () => setIsModalOpen(true);

  return (
    <div className="bg-gray-100 min-h-screen">
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://pngimg.com/uploads/amazon/amazon_PNG5.png"
        />
      </Head>
      <Header />
      <div className="mx-auto py-6">
        <button className="inline-flex" onClick={() => router.back()}>
          <FaArrowLeft />
        </button>
        <br />
        <span className="text-gray-300">|</span>
        <h3 className="font-bold text-2xl">
          {product.category}
        </h3>
        <br />
        <ProductDetail product={product} onImageClick={openModal}  rating={rating} />
        <Footer />

        <Transition show={isModalOpen} as={Fragment}>
          <Dialog as="div" className="fixed inset-0 z-10 overflow-y-auto" onClose={closeModal}>
            <div className="min-h-screen px-4 text-center image-modal">
              <Dialog.Overlay className="fixed inset-0 bg-black opacity-30" />

              <span
                className="inline-block h-screen align-middle"
                aria-hidden="true"
              >
                &#8203;
              </span>
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
              >
                <div className="inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-2xl">
                  <Dialog.Title as="h3" className=" absolute text-lg font-medium leading-6 text-gray-900">
                    {product.title}
                  </Dialog.Title>

                  <div className="mt-2">
                    <img src={product.image} alt={product.title} className="w-full" />
                  </div>

                  <div className="mt-4">
                    <button
                      type="button"
                      className="inline-flex justify-center px-4 py-2 text-sm font-medium text-blue-900 bg-blue-100 border border-transparent rounded-md hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset
                      focus-visible:ring-blue-500"
                      onClick={closeModal}
                    >
                      Close
                    </button>
                  </div>
                </div>
              </Transition.Child>
            </div>
          </Dialog>
        </Transition>
      </div>
    </div>
  );
}

export default ProductPage;
