import { useRouter } from 'next/router';
import Header from '../../components/Header';
import ProductDetail from '../../components/ProductDetail';
import { FaArrowLeft } from "react-icons/fa";
import Head from "next/head";

export async function getServerSideProps(context) {
  const { pid } = context.query;
  const product = await fetch(
    `https://fakestoreapi.com/products/${pid}`
  ).then((res) => res.json());

  return {
    props: {
      product,
    },
  };
}

function ProductPage({ product }) {
  const router = useRouter();

  return (
    <div className="bg-gray-100 min-h-screen">
       <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://pngimg.com/uploads/amazon/amazon_PNG5.png"
        />
      </Head>
      <Header />
      <div className="mx-auto py-6">
        <button className="inline-flex" onClick={() => router.back()}>
          <FaArrowLeft />
          </button>
          <br />
          <span className="text-gray-300">|</span>
          <h3 className="font-bold text-2xl">
            {product.category}
          </h3>
          <br />
        <ProductDetail product={product} />
      </div>
    </div>
  );
}

export default ProductPage;
